$(document).ready(function(){
		$('.rounded_header.closable').click(function()
		{
			if($(this).children('h1').children('span.open_close_arrow').children('i').hasClass('icon-angle-up'))
			{
				$(this).children('h1').children('span.open_close_arrow').children('i').removeClass('icon-angle-up');
				$(this).children('h1').children('span.open_close_arrow').children('i').addClass('icon-angle-down');
			}
			else
			{
				$(this).children('h1').children('span.open_close_arrow').children('i').removeClass('icon-angle-down');
				$(this).children('h1').children('span.open_close_arrow').children('i').addClass('icon-angle-up');
			}
			/*$(this).parent().parent('.rounded_header').slideToggle('slow');*/
			$(this).next('.rounded_content').slideToggle('slow',function()
			{
				$(this).prev().toggleClass('closed');
			});
		});
	});